@startuml
!include style.puml
mainframe sd get descriptor

box Logic LOGIC_COLOR_T1
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "descriptor:ArgumentMultimap" as ArgMultimap LOGIC_COLOR
participant "predicate:FindPersonPredicate" as FindPersonPredicate LOGIC_COLOR
end box


activate FindCommandParser
FindCommandParser -> FindCommandParser : createDescriptor(" n/alice")
activate FindCommandParser
create ArgMultimap
FindCommandParser -> ArgMultimap
activate ArgMultimap
ArgMultimap --> FindCommandParser : descriptor
deactivate ArgMultimap

FindCommandParser --> FindCommandParser : descriptor
deactivate FindCommandParser

create FindPersonPredicate
FindCommandParser -> FindPersonPredicate : FindPersonPredicate(descriptor)
activate FindPersonPredicate
FindPersonPredicate --> FindCommandParser : predicate
@enduml
