

@startuml

start
:press UP/DOWN arrow-key;

if (Exist previous/next command) then (yes)
  :pointer decreases/increases;
  :fetch the result from list;
  :fill into the textbox;
else ([else])
  :throw exception;
  :show error message;
endif

stop

@enduml
