@startuml
!include style.puml
skinparam ClassFontColor BLACK_COLOR
skinparam ClassBorderColor BLACK_COLOR
skinparam ClassHeaderBackgroundColor ORANGE_COLOR

title Initial

package stateHistory {
    class State0 as "__state0:AddressBook__"
    class State1 as "__state1:AddressBook__"
    class State2 as "__state2:AddressBook__"
}

State0 -[hidden]right-> State1
State1 -[hidden]right-> State2

hide State1
hide State2

class Pointer as "currentStateIndex" WHITE_COLOR
Pointer -up-> State0
@end
